name: i18n Check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  i18n-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: yarn install & build
        run: |
          yarn install
          yarn build
      - name: yarn i18n:check
        run: |
          yarn i18n:check --locales translations/messageExamples --source en-US
