name: i18n Check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  i18n-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: pnpm install & build
        run: |
          pnpm install
          pnpm build
      - name: pnpm i18n:check
        run: |
          pnpm i18n:check --locales translations/messageExamples --source en-US
