name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm ci

      - name: Build
        run: pnpm build

      - name: Publish package to NPM
        run: npm publish --access public
